// This file is automatically generated by qtc from "party.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line party.qtpl:1
package templates

//line party.qtpl:1
import "github.com/fpawel/ankat/data/dataproducts"

//line party.qtpl:2
import "fmt"

//line party.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line party.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line party.qtpl:4
func StreamParty(qw422016 *qt422016.Writer, p dataproducts.PartyInfo) {
	//line party.qtpl:4
	qw422016.N().S(`
<html> 
	<head> 
        <title> Партия</title>
        <style type="text/css"> 
            table, th, td { 
                border-collapse: collapse; 
            }
            th, td { 
                font-size: 14px; 
                padding: 5px 8px;
            }
            .col2 {
                color: #000080; 
                font-weight: bold; 
            } 
        </style> 
    </head>
    <body>
    <h3> 
        Параметры партии № `)
	//line party.qtpl:24
	qw422016.N().D(int(p.PartyID))
	//line party.qtpl:24
	qw422016.N().S(` от `)
	//line party.qtpl:24
	qw422016.E().S(fmt.Sprintf("%s", p.CreatedAt.Format("02 01 2006")))
	//line party.qtpl:24
	qw422016.N().S(` 
    </h3>
    </body>
</html>
`)
//line party.qtpl:28
}

//line party.qtpl:28
func WriteParty(qq422016 qtio422016.Writer, p dataproducts.PartyInfo) {
	//line party.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line party.qtpl:28
	StreamParty(qw422016, p)
	//line party.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line party.qtpl:28
}

//line party.qtpl:28
func Party(p dataproducts.PartyInfo) string {
	//line party.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
	//line party.qtpl:28
	WriteParty(qb422016, p)
	//line party.qtpl:28
	qs422016 := string(qb422016.B)
	//line party.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
	//line party.qtpl:28
	return qs422016
//line party.qtpl:28
}
