// This file is automatically generated by qtc from "party.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line view\party.qtpl:1
package view

//line view\party.qtpl:1
import "github.com/fpawel/ankat/dataankat/dataproducts"

//line view\party.qtpl:2
import "github.com/fpawel/ankat"

//line view\party.qtpl:3
import "fmt"

//line view\party.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view\party.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view\party.qtpl:5
func StreamParty(qw422016 *qt422016.Writer, p dataproducts.Party, funcVarName func(ankat.Var) string) {
	//line view\party.qtpl:5
	qw422016.N().S(`
<html> 
	<head> 
        <title> Партия</title>
        <style type="text/css"> 
            table, th, td { 
                border-collapse: collapse; 
                border:0px;
            }
            th, td { 
                font-size: 14px; 
                padding: 5px 8px;
            }
            .col2 {
                color: #000080; 
                font-weight: bold; 
                text-align:left;
            } 
            .col1 {
                text-align:right;
            }

            table.tab2, table.tab2 th, table.tab2 td {
                border: 1px solid black;
            }
        </style> 
    </head>
    <body>

    `)
	//line view\party.qtpl:35
	varValues := p.ProductVarValues()

	//line view\party.qtpl:36
	qw422016.N().S(`

    `)
	//line view\party.qtpl:38
	for _, sect := range varValues.Sects() {
		//line view\party.qtpl:38
		qw422016.N().S(`    
        <h3>`)
		//line view\party.qtpl:39
		qw422016.E().S(sect.Description())
		//line view\party.qtpl:39
		qw422016.N().S(`</h3>
        <table class="tab2"> 
            <thead>
                <tr>
                    <th colspan = "2">Точка</th> 
                    `)
		//line view\party.qtpl:44
		for _, product := range varValues.Products() {
			//line view\party.qtpl:44
			qw422016.N().S(`
                        <th>`)
			//line view\party.qtpl:45
			qw422016.E().V(product)
			//line view\party.qtpl:45
			qw422016.N().S(`</th>
                    `)
			//line view\party.qtpl:46
		}
		//line view\party.qtpl:46
		qw422016.N().S(` 
                </tr>
            </thead>           
            <tbody>
               
                `)
		//line view\party.qtpl:51
		for _, v := range varValues.Vars() {
			//line view\party.qtpl:51
			qw422016.N().S(`
                    `)
			//line view\party.qtpl:52
			for _, pt := range varValues.Points() {
				//line view\party.qtpl:52
				qw422016.N().S(`

                        `)
				//line view\party.qtpl:54
				if xs, ok := varValues.SectVarPointValues(sect, v, pt); ok {
					//line view\party.qtpl:54
					qw422016.N().S(`
			                <tr>
                                <th style="text-align:left;" >`)
					//line view\party.qtpl:56
					qw422016.E().S(sect.PointDescription(pt))
					//line view\party.qtpl:56
					qw422016.N().S(`</th> 
                                <th style="text-align:right;" >`)
					//line view\party.qtpl:57
					qw422016.E().S(fmt.Sprintf("%s [%d]", funcVarName(v), int(pt)))
					//line view\party.qtpl:57
					qw422016.N().S(`</th>
                                `)
					//line view\party.qtpl:58
					for _, product := range varValues.Products() {
						//line view\party.qtpl:58
						qw422016.N().S(`
                                    <td style="text-align:left;">
                                        `)
						//line view\party.qtpl:60
						if value, ok := xs[product]; ok {
							//line view\party.qtpl:60
							qw422016.N().S(`
                                            `)
							//line view\party.qtpl:61
							qw422016.N().F(value)
							//line view\party.qtpl:61
							qw422016.N().S(`
                                        `)
							//line view\party.qtpl:62
						}
						//line view\party.qtpl:62
						qw422016.N().S(`
                                    </td>
                                `)
						//line view\party.qtpl:64
					}
					//line view\party.qtpl:64
					qw422016.N().S(` 
                            </tr>
			            `)
					//line view\party.qtpl:66
				}
				//line view\party.qtpl:66
				qw422016.N().S(`
                    `)
				//line view\party.qtpl:67
			}
			//line view\party.qtpl:67
			qw422016.N().S(`
                `)
			//line view\party.qtpl:68
		}
		//line view\party.qtpl:68
		qw422016.N().S(`
            </tbody>
        </table>        
    `)
		//line view\party.qtpl:71
	}
	//line view\party.qtpl:71
	qw422016.N().S(`   

    `)
	//line view\party.qtpl:73
	if len(p.Coefficients()) > 0 {
		//line view\party.qtpl:73
		qw422016.N().S(`
        `)
		//line view\party.qtpl:74
		StreamCoefficients(qw422016, p)
		//line view\party.qtpl:74
		qw422016.N().S(`

    `)
		//line view\party.qtpl:76
	}
	//line view\party.qtpl:76
	qw422016.N().S(` 

    

    </body>
</html>
`)
//line view\party.qtpl:82
}

//line view\party.qtpl:82
func WriteParty(qq422016 qtio422016.Writer, p dataproducts.Party, funcVarName func(ankat.Var) string) {
	//line view\party.qtpl:82
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view\party.qtpl:82
	StreamParty(qw422016, p, funcVarName)
	//line view\party.qtpl:82
	qt422016.ReleaseWriter(qw422016)
//line view\party.qtpl:82
}

//line view\party.qtpl:82
func Party(p dataproducts.Party, funcVarName func(ankat.Var) string) string {
	//line view\party.qtpl:82
	qb422016 := qt422016.AcquireByteBuffer()
	//line view\party.qtpl:82
	WriteParty(qb422016, p, funcVarName)
	//line view\party.qtpl:82
	qs422016 := string(qb422016.B)
	//line view\party.qtpl:82
	qt422016.ReleaseByteBuffer(qb422016)
	//line view\party.qtpl:82
	return qs422016
//line view\party.qtpl:82
}

//line view\party.qtpl:84
func StreamCoefficients(qw422016 *qt422016.Writer, p dataproducts.Party) {
	//line view\party.qtpl:84
	qw422016.N().S(`

    `)
	//line view\party.qtpl:87
	values := p.Coefficients()

	//line view\party.qtpl:88
	qw422016.N().S(`

    <h3>Коэффициенты</h3>

    <table class="tab2">
        <thead>
            <th>№</th>
            `)
	//line view\party.qtpl:95
	for _, product := range values.Products() {
		//line view\party.qtpl:95
		qw422016.N().S(`
                <th>`)
		//line view\party.qtpl:96
		qw422016.N().D(int(product))
		//line view\party.qtpl:96
		qw422016.N().S(`</th>
            `)
		//line view\party.qtpl:97
	}
	//line view\party.qtpl:97
	qw422016.N().S(`
        </thead>
        <tbody>
            `)
	//line view\party.qtpl:100
	for _, coefficient := range values.Coefficients() {
		//line view\party.qtpl:100
		qw422016.N().S(`       
                <tr>
                    <th>`)
		//line view\party.qtpl:102
		qw422016.E().S(fmt.Sprintf("%02d", coefficient))
		//line view\party.qtpl:102
		qw422016.N().S(`</th>                        
                    `)
		//line view\party.qtpl:103
		for _, product := range values.Products() {
			//line view\party.qtpl:103
			qw422016.N().S(`
                        <td>`)
			//line view\party.qtpl:104
			qw422016.E().V(formatFloat6(values[coefficient][product]))
			//line view\party.qtpl:104
			qw422016.N().S(`</td>
                    `)
			//line view\party.qtpl:105
		}
		//line view\party.qtpl:105
		qw422016.N().S(` 
                </tr>
	        `)
		//line view\party.qtpl:107
	}
	//line view\party.qtpl:107
	qw422016.N().S(`
        </tbody>
        
    </table>

`)
//line view\party.qtpl:112
}

//line view\party.qtpl:112
func WriteCoefficients(qq422016 qtio422016.Writer, p dataproducts.Party) {
	//line view\party.qtpl:112
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view\party.qtpl:112
	StreamCoefficients(qw422016, p)
	//line view\party.qtpl:112
	qt422016.ReleaseWriter(qw422016)
//line view\party.qtpl:112
}

//line view\party.qtpl:112
func Coefficients(p dataproducts.Party) string {
	//line view\party.qtpl:112
	qb422016 := qt422016.AcquireByteBuffer()
	//line view\party.qtpl:112
	WriteCoefficients(qb422016, p)
	//line view\party.qtpl:112
	qs422016 := string(qb422016.B)
	//line view\party.qtpl:112
	qt422016.ReleaseByteBuffer(qb422016)
	//line view\party.qtpl:112
	return qs422016
//line view\party.qtpl:112
}
